<img src="img/wild-life-of-your-home-1.jpg">

<p class="intro"><em>The Wildlife of Your Home</em> is a research project that aims to study bacteria living in peoples' homes and relate that data to each person's lifestyle.</p>

<img src="img/wild-life-of-your-home-2.jpg">

<h2>Designed through drawing</h2>
<p>The data collected in this project was very difficult to understand. We had a lot of meetings and took text notes over many months, but some of the most successful meetings involved pictures. I like working with a client while drawing pictures of what I think they're asking for. It can really accelerate the process of creation.</p>

<p>The picture above for example was the sort of data plot that they were trying to make use of. It was automatically generated by super computers, and not that useful to look at for anyone without a lot of explanation. I determined after a lot of sketching that what they were trying to show was how your bacteria was different from another person's bacteria. But they didn't have the results from the study yet so that they could show that. So I suggested making personas—a technique that is used in design all the time.</p>

<img src="img/wild-life-of-your-home-3.jpg">

<p>Seen above might be the amount of bacteria in your kitchen, and you own a small dog. Jill is a persona that owns a big dog, and her obfuscated bio would reflect that. As a user you would be able to draw your own hypotheses about the data while the research was still being done. Citizen science is often about presenting data to everyday people and asking them to identify trends.</p>
